DROP TABLE IF EXISTS dbo.UdzialyWKursach;
DROP TABLE IF EXISTS dbo.Studenci;
DROP TABLE IF EXISTS dbo.Kursy;
DROP TABLE IF EXISTS dbo.Kierunki;
DROP TABLE IF EXISTS dbo.Pracownicy;
DROP TABLE IF EXISTS dbo.Katedry;